version: "3"
services:
  mongo:
    image: "mongo:4"
    ports:
      - "27017:27017"
    expose:
      - 27017
  app:
    build: "."
    ports:
      - "8080:8080"
    volumes:
      - ".:/app/twitterish"
    depends_on:
      - "mongo"